### ISSUE TITLE
Clarify restart implications of a service tree?

### ISSUE THREAD

**Issue by calmh** [thejerf/suture#10]
I'm not sure I understand this:

> Supervisors are also services, so you can create a
> tree structure here, depending on the exact combination of restarts
> you want to create.

Given a tree with a top level supervisor, a child supervisor and three services:

```
Sup1
 |
 +- Sup2
 |    |
 |    +- ServA
 |    +- ServB
 |
 +- ServC
 ```

What would differ in this setup, restart wise, compared to hanging all the services directly off of "Sup1"? I don't see there being a difference regardless of whether ServA, ServB or ServC fails...

(The differences I've found is that this makes more sense when "Sup2" is an object created somewhere that internally has two or more things to do that should not be exposed upwards... And also that handling restart logging gets to be a pain in the ass since that needs to be overridden on each supervisor... :)

**Comment by thejerf** [comment]
That would allow you to shut down Sup2 without affecting ServC. The other big thing is the complement of what you're complaining about :), which is that if you really need some different settings the sub-supervisor can have them. I have encountered that once, but do not consider it a huge case. (YMMV.)

I think the advantage is in another dimension entirely; you can create a package or public library that does $WHATEVER, and the interface it exposes is that there is a single object for the user to deal with that represents all runtime service functionality for it. In general I wouldn't expect to see the tree you outlined within a single function.

**Comment by calmh** [comment]
No, exactly, the second paragraph is why I'm doing this. The only annoyance is the logging "flexbility", but it's only a few more lines of code to write so that's fine. All good.

**Comment by thejerf** [comment]
I'm listening; can you express a more clear use case, or do you have a suggestion we can consider? It's hard to solve a problem I don't have, but I definitely believe you have one and am open to discussion on its nature.

**Comment by calmh** [comment]
No, I don't think I have a problem, it's all good. For my use case it would have been nice if logging magically bubbled up to the "main" supervisor, as I can attach a log handler there once and for all. But in my case all the sub packages are under my control so I can do the right thing where I instantiate a new Supervisor. However, had I used someone else's package that used suture and staid with the defaults I would have to fork it to get rid of them logging restarts that I don't want to show the users.

**Comment by thejerf** [comment]
An intriguing thought. It would technically be legal for a supervisor to penetrate the Service abstraction for itself. I'd definitely only want to propagate the logging info, though; the rest of the params should stay the same. Obviously.

Going back to my inspiration, IIRC Erlang technically really gives you little control over the supervisor logging, by using a standard logging package, which I gather nobody particularly likes....

I'm going to sleep on it and see what pops out. At the moment my intuition is comfortable with the idea, though.

**Comment by thejerf** [comment]
Urf. How time flies. I've pushed this now. It seems a good idea. We'll see if somebody complains and demands to be able to set separate logs... but even if they do I suspect I'd make it a separate function because this is still a better _default_ behavior.
