### ISSUE TITLE
Supervisor.state may need locking?

### ISSUE THREAD

**Issue by calmh** [thejerf/suture#11]
As far as I understand, Add()ing services to a running Supervisor should be fine. But it's not, in some cases. Specifically, adding services to child supervisors causes a data race. Have I misunderstood the API here?

Reproduction: https://gist.github.com/1b1c0d37a167d7e9fa2d

```
$ go run -race datarace.go 
==================
WARNING: DATA RACE
Read by main goroutine:
  github.com/thejerf/suture.(*Supervisor).Add()
      /Users/jb/src/github.com/thejerf/suture/suture.go:376 +0x231
  main.(*someService).AddChild()
      /Users/jb/sutrace/datarace.go:47 +0x133
  main.main()
      /Users/jb/sutrace/datarace.go:25 +0x1b4

Previous write by goroutine 7:
  github.com/thejerf/suture.(*Supervisor).Serve()
      /Users/jb/src/github.com/thejerf/suture/suture.go:420 +0x216
  main.(*someService).Serve()
      <autogenerated>:17 +0x55
  github.com/thejerf/suture.(*Supervisor).runService.func1()
      /Users/jb/src/github.com/thejerf/suture/suture.go:537 +0x6b

Goroutine 7 (running) created at:
  github.com/thejerf/suture.(*Supervisor).runService()
      /Users/jb/src/github.com/thejerf/suture/suture.go:540 +0x5e
  github.com/thejerf/suture.(*Supervisor).Serve()
      /Users/jb/src/github.com/thejerf/suture/suture.go:447 +0xdc7
==================
tick on one
tick on two
tick on four
tick on three
^Cexit status 2
```

In actual reality this hits me when the individual services (`someService` in the example) reloads config during runtime and discovers that they need to do more stuff than they already did - for example open another port for listening, and then adding that service to themselves.

**Comment by thejerf** [comment]
> Specifically, adding services to child supervisors causes a data race. 

Nope, you've filed a bug. I'll have a look at this later today.

**Comment by thejerf** [comment]
Thank you. I was able to boil down a replication test case for the test suite. Version 1.0.1 is now released.

**Comment by calmh** [comment]
Thanks!

**Comment by thejerf** [comment]
Whoops, apparently the commit message never closed this.
