### ISSUE TITLE
Stopping sequence unclear

### ISSUE THREAD

**Issue by advanderveer** [thejerf/suture#14]
According to the documentation on .Stop(): 
```
Stop stops the Supervisor.

This function will not return until either all Services have stopped, or they timeout after the timeout value given to the Supervisor at creation.
```

To me this suggest supervisor will wait for each .Stop() implementation to finish but with the following example program:

```
package main

import (
	"fmt"
	"os"
	"os/signal"
	"time"

	"github.com/thejerf/suture"
)

type A struct{}

func (a *A) Serve() {
	for {
		fmt.Println("A")
		<-time.After(time.Second * 5)
	}
}

func (a *A) Stop() {
	<-time.After(time.Second * 10)
}

func main() {
	exit := make(chan os.Signal)
	signal.Notify(exit, os.Interrupt)

	visor := suture.NewSimple("main")
	visor.Add(&A{})
	visor.ServeBackground()

	<-exit

	fmt.Println("Stopping")
	visor.Stop()
	fmt.Println("Stopped")
}
```

Whenever I send a signal over the <-exit channel the program will exit immediately, instead I want to allow services to shutdown gracefully (possibly taking several seconds), how would I go about doing this?

**Comment by thejerf** [comment]
Yes.... I'm not sure how this worked for the person who reported this issue in the first place, because it doesn't wait at all. I've got a tentative patch but it's failing the tests, so I'm going to have to work with it a bit more tonight.

The answer is that your code is supposed to be correct for your desired purpose.

**Comment by advanderveer** [comment]
Ok cool! Is there an old working commit I can use in the meantime? Also, awesome work on this project overall, let me know if you need any help.

**Comment by thejerf** [comment]
There's a v1.1.1 you can now try out; let me know if it works for you. If it does I'll merge it into master and tag it.

**Comment by advanderveer** [comment]
Its working as I expect it to. Thanks for the quick response and keep it up!

**Comment by thejerf** [comment]
Merged in to master, along with some other tweakups discovered in testing.
