### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by csterritt** [thejerf/suture#30]
Hello -- this looks like quite a useful library, thanks for implementing it.

One thing I noticed... the documentation for `RemoveAndWait` ends abruptly on (what appears to be) a sentence fragment:

    /*
    RemoveAndWait will remove the given service from the Supervisor and attempt
    to Stop() it. It will wait up to the given timeout value for the service to
    terminate. A timeout value of 0 means to wait forever.

    If a nil error is returned from this function
    */

Please resolve this cliffhanger :-)

**Comment by thejerf** [comment]
Thank you. I hope the wait was worth it.
