### ISSUE TITLE
Jitter backoff duration

### ISSUE THREAD

**Issue by lthibault** [thejerf/suture#32]
# Problem Statement

When multiple services crash because an underlying network resource _R_ becomes unavailable, they will tend to enter/exit their backoff states in synchrony, and contend for _R_ when it comes back online.

Adding a random jitter to the backoff duration can drastically improve performance under these conditions.  A more detailed writeup can be found [here](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/).

# Proposal

Currently, the backoff duration is specified by [`Supervisor.failureBackoff`](https://github.com/thejerf/suture/blob/master/supervisor.go#L99), of type `time.Duration`.  I propose we change its type to something like:

```go
type Duration interface {
    Duration() time.Duration
}
```

This would provide users with full control over how backoff intervals are generated, allowing jitter to be trivially implemented.  Fixed durations could be specified by another type.

```go
type FixedDuration time.Duration

func (d FixedDuration)  Duration() time.Duration { return time.Duration(d) }
```

@thejerf What are your thoughts on this?  I wanted to ask before submitting a PR, but I'd be happy to implement this myself.

**Comment by thejerf** [comment]
Changing type would require rolling a 3.0. I think it would be better to:

1. Add a field as you describe
2. Implement a useful default jitter (I'm a fan of (basetime + rand(0,0.5)*basetime) myself.)
3. Make the new default in the supervisor use the new sensible jitter, so anyone that didn't specify a concrete failureTimeout automatically gets a jitter.
4. Actually remove the documentation for failureBackoff, excepting a note that it is available for backwards compatibility.

That way the documentation advances like it's a global change, and new users get guided towards using the sensible jitter implementation, but it stays reverse compatible.

**Comment by lthibault** [comment]
Ok, that seems reasonable to me.

>Add a field as you describe

I didn't suggest adding a field, so this part has me a bit confused.  Are you suggesting we add a field to `suture.Spec`, or `suture.Supervisor (or both)?

**Comment by thejerf** [comment]
Sorry, I meant, "add a new field of the type as you describe". I'm trying to avoid an interface change that would require a new major version, but I want to turn on jitter by default.

**Comment by lthibault** [comment]
Ok, gotcha.

Another approach might be to combine the existing `FailureBackoff` with something like the [`jitterbug.Jitter`](https://godoc.org/github.com/lthibault/jitterbug#Jitter) interface:

```go
type Jitter interface {
     // Returns the sum of the input duration and a randomly drawn jitter
    Jitter(time.Duration) time.Duration
}
```

The procedure would be as follows:

1. Add `Jitter` field to `suture.Spec` and `suture.Supervisor`
2. Use `failureBackoff` as a basetime, which is fed into the `Jitter()` method to obtain the _actual_ backoff time.

**Advantages:**

1.  No longer need to deprecate `failureBackoff`
2. A sensible default jitter can still be implemented
3. Suture's jitter becomes fully compatible with the [`jitterbug`](https://github.com/lthibault/jitterbug) library, which is nice.

All in all, this seems like a less invasive operation.  What do you think?

**Comment by lthibault** [comment]
@thejerf I think my above proposal is more clearly illustrated in code, so I've submitted the above PR.

**Comment by thejerf** [comment]
Sorry, I bobbled the email on this. It looks pretty good, except I'm going to remove `func init() { rand.Seed(time.Now().UnixNano()) }` and put a rand.Rand on each Supervisor if it needs a jitter source. I don't like messing with the global random number generator if I don't have to.

**Comment by lthibault** [comment]
Agree with the init/rand.Rand.

**Comment by thejerf** [comment]
After some thought, I think changing the default behavior of the backoff is worth bumping the major version. But I also think that I _want_ to change the default behavior, and I recall seeing the Erlang VM make changes like this by default, so I don't think it's out of line to make such policy changes be the default. So v3.0.0 should be up and available now. 

Thank you very much!
