### ISSUE TITLE
Supervisor reports a timeout even though all services successfully stopped

### ISSUE THREAD

**Issue by narkq** [thejerf/suture#34]
This happens if `Supervisor.Stop()` is called right after `RemoveAndWait()`-ing a service.
Also, `Supervisor.Stop()` does not return until its timeout expires.
Inserting a brief `time.Sleep()` right before `Supervisor.Stop()` makes the issue disappear.

Code reproducing the issue: https://github.com/narkq/suture/commit/20b53904856780441a37b0d2f3af23211952cad6

**Comment by thejerf** [comment]
Thank you. I will have a look at this in the next few days and see what I can do. Holiday times, etc.
