### ISSUE TITLE
Is there an example of using suture with multiple levels of supervision?

### ISSUE THREAD

**Issue by lherman-cs** [thejerf/suture#36]

**Comment by thejerf** [comment]
There's no trick to it; supervisors are Services, so you can add supervisors to other supervisors no problem.

```
toplevel := suture.NewSimple("top level")
subsupervisor := suture.NewSimple("subsupervisor")
toplevel.Add(subsupervisor)
```

I recommend against looping, though theoretically nothing will go wrong as long as the supervisors themselves never crash.

The test cases cover it too: https://github.com/thejerf/suture/blob/master/suture_test.go#275
