### ISSUE TITLE
Request: Add check if supervisor.Stop was successful

### ISSUE THREAD

**Issue by imsodin** [thejerf/suture#37]
In our shutdown code on Syncthing we need to close a database once all services are stopped. If the services aren't actually stopped and the supervisor just timed out, that can lead to panics. It would be very helpful if `Supervisor.Stop` returned an error or alternatively to not change the signature, if there was a `Supervisor.Error() error` (or `StopError`, or `TimedOut() bool`) method to indicate a unsuccessful stop.

**Comment by thejerf** [comment]
Yes, I believe I'll need it to be a new method specifically on the supervisor, but that sounds reasonable.

I'll have a look at this in the next few days. I will certainly be sure to have some sort of distinguished error that lets you be sure that is the problem.

I'll also look into whether the error can yield useful information about which services appear to have timed out. There will have to be a big fat warning on that about the possibility of TOCTOU issues but it seems like it's still the sort of thing that may be theoretically dangerous to use, but practically useful.

**Comment by thejerf** [comment]
After examining the failure states, there isn't really an "error" per se to be returned, so I return a concrete report object containing all the information that may be of interest. That way you don't need to cast anything to get that information out.

I hope this meets your needs.
