### ISSUE TITLE
how do u use this as a webserver with something like fasthttp or net/http

### ISSUE THREAD

**Issue by gitmko0** [thejerf/suture#47]
any examples of production usage for web server services?
i'm new to erlang but hope to see some sample code for this in golang

**Comment by thejerf** [comment]
I don't. The webserver has never crashed on me, so I don't use suture to wrap it. I spawn it off in its own goroutine(s), have a paranoid wrapper that logs any error that occurs and terminates the program, and I've never seen it fire.
