### ISSUE TITLE
Tests fail with race detector enabled

### ISSUE THREAD

**Issue by iwittkau** [thejerf/suture#56]
While assessing if I could use this project in production I ran the tests with the `-race` flag and discovered some data races.  
Fortunately, I can report that these races come from how the tests were written.

Also I found this:

```go
// http://golangtutorials.blogspot.com/2011/10/gotest-unit-testing-and-benchmarking-go.html
// claims test function are run in the same order as the source file...
// I'm not sure if this is part of the contract, though. Especially in the
// face of "t.Parallel()"...
//
// This is also why all the tests must go in this file; this test needs to
// run last, and the only way I know to even hopefully guarantee that is to
// have them all in one file.
func TestEverMultistarted(t *testing.T) {
```

I can provide a PR with the fixes, enabling parallel testing.

After that, you should be able to split the tests up again.

**Comment by thejerf** [comment]
Sure, thank you.

I have run them with the race detector, but, of course, it can yield false negatives, and is sensitive to the little details that change between versions and such.
