### ISSUE TITLE
Unable to close the supervised service gracefully if it panic

### ISSUE THREAD

**Issue by boolafish** [thejerf/suture#58]
### Note

Discovered this while playing around to see how the supervisor would restart a panic service.
It can indeed restart a panic service usually. However, if a service was panicked (for some times) and caused the supervisor to backoff. There will be a period where the supervisor cannot close the service properly (out of time)

It seems to be from here:
https://github.com/thejerf/suture/blob/783dc5802796c4a88253bc69219ecf3040bfdd52/v4/supervisor.go#L534-L549

there is a `blockingCancellation` which need to wait the `done` channel to be closed. However, in the case of panic, we do not close the channel in the `defer - recover` part. As a result, when the supervisor tries to cancel the service, it will be blocked until timeout.

**Comment by thejerf** [comment]
Thank you for this report. I have been quite ill the past couple of weeks, and it will still probably be a bit before I get to addressing this as I'm still not feeling all that well.

**Comment by boolafish** [comment]
Oh take care. Hope you get well soon!!
