### ISSUE TITLE
Supervisor panics when catching non-string panic value

### ISSUE THREAD

**Issue by lthibault** [thejerf/suture#59]
The v4 supervisor [type-asserts recovered values as string](https://github.com/thejerf/suture/blob/master/v4/supervisor.go#L546).  This causes the supervisor to panic when attempting to recovery any other value.  Unfortunately, it is quite common for library code to panic `error` or other application-specific types.

Is there any reason preventing us from recovering an `interface{}` and relying on the user to inspect the value in `EvtHandler`?

I submit that this should be considered a bug, since it breaks one of the key promises of the `Supervisor` contract:  recovery from arbitrary failures.

**Comment by thejerf** [comment]
Undeniably a bug. That's definitely one of those "who wrote that? oh crap, it was me!" moments.

Any objection to rewriting that to `fmt.Sprintf("%v", r)`? That's usually what I use but I figure I'll run it by you before I hurry and commit this. Changing it to something other than a string would technically be a breaking change.

**Comment by lthibault** [comment]
>That's definitely one of those "who wrote that? oh crap, it was me!"

That is a very familiar feeling for me as well! 😅 

>Any objection to rewriting that to fmt.Sprintf("%v", r)?

None whatsoever, though perhaps we should make this use-configurable?  I can think of cases where I might want to apply special formatting (`%#v`, or something more elaborate).

In the meantime, I'll send over a PR in a couple of minutes.  Thanks for your quick response on this issue :)
