### ISSUE TITLE
Test panics with deadlock

### ISSUE THREAD

**Issue by zepatrik** [thejerf/suture#66]
On current master I reliably get
```
=== RUN   TestFailingSupervisors
=== PAUSE TestFailingSupervisors
=== CONT  TestFailingSupervisors
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan receive]:
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1412 +0x4a5
testing.tRunner(0xc0001184e0, 0xc000069cd8)
	/usr/lib/go/src/testing/testing.go:1452 +0x144
testing.runTests(0xc0001300a0?, {0x63a120, 0x1c, 0x1c}, {0x7f3179a4aa68?, 0x40?, 0x0?})
	/usr/lib/go/src/testing/testing.go:1844 +0x456
testing.(*M).Run(0xc0001300a0)
	/usr/lib/go/src/testing/testing.go:1726 +0x5d9
main.main()
	_testmain.go:103 +0x1aa

goroutine 18 [chan send]:
github.com/thejerf/suture/v4.TestFailingSupervisors(0xc000118680)
	/home/patrik/git/suture/v4/suture_test.go:571 +0x487
testing.tRunner(0xc000118680, 0x551b10)
	/usr/lib/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1493 +0x35f

goroutine 19 [select]:
github.com/thejerf/suture/v4.(*Supervisor).Serve(0xc00014e140, {0x579308?, 0xc00011a7c0?})
	/home/patrik/git/suture/v4/supervisor.go:355 +0x473
created by github.com/thejerf/suture/v4.TestFailingSupervisors
	/home/patrik/git/suture/v4/suture_test.go:534 +0x28a
```

When reverting https://github.com/thejerf/suture/commit/0cef8e873ae3184dcdedffd41b5f02e7b46dbe32 this test passes. I am not sure what the context of the test exactly is, so whether the test or the patch is incorrect.

**Comment by thejerf** [comment]
I'm getting a different manifestation, but I'm definitely getting problems. I know I ran the tests before the release, so I wonder if a compiler change has revealed a subtle issue, because I haven't run them on the past couple of Go versions.

**Comment by thejerf** [comment]
I've ended up removing the test. I can see why it was sometimes managing to pass, but with the new context-based approach, it's unsound in general. Thank you for catching this and reporting it.

**Comment by zepatrik** [comment]
Thanks for clarifying, I was not sure whether the test or the code is the problem :+1:
