### ISSUE TITLE
CI status badge says: build unknown

### ISSUE THREAD

**Issue by marco-m** [thejerf/suture#71]
Hello,
the badge at the top of the README shows `build unknown`
![suture](https://github.com/thejerf/suture/assets/3075069/41c28a85-c112-4e21-9b58-2dd9d5a8b70c)

If I follow the link to Travis CI, https://travis-ci.org/thejerf/suture,

it tells me
"We couldn't display the repository thejerf/suture. This repository may not exist or you may need to Sign in"
![travis](https://github.com/thejerf/suture/assets/3075069/b866a1c0-4a9b-46a4-8e6e-5d850354c363)

**Comment by thejerf** [comment]
Oh yeah, they closed that down, I think. Never was a huge win anyhow.
