### ISSUE TITLE
EventStopTimeout exposes all struct field values.

### ISSUE THREAD

**Issue by flowchartsman** [thejerf/suture#73]
As mentioned in #72, EventStopTimeout prints all struct field values of the incoming service in its `String()` method, potentially exposing secret data.  This seems likely to be a typo on [line 52 of events.go](https://github.com/thejerf/suture/blob/master/v4/events.go#L52) where `e.Service` is passed to `fmt.Sprintf` instead of `e.ServiceName`, as it is done throughout the rest of the file.

This behavior is thanks to an implicit (and frankly poorly-documented) [identical handling of `%s` and `%v`](https://go.dev/play/p/3ulgt1sTQfZ) in the case of struct types (and pointers to those types) when the type otherwise does not satisfy any printing interface. Essentially, the value falls all the way through to`pp.printValue` [here](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/fmt/print.go;l=834-854).

Fortunately, the fix does not need to involve reflection as with #72, but simply replacing `e.Service` with `e.ServiceName`.

**Comment by thejerf** [comment]
I'm going to take a swing through the entire logging stack this weekend. Without making any backwards incompatible changes I'd like to offer a default slog-based implementation too.

I'll take a look at this then.

**Comment by flowchartsman** [comment]
Took a crack at that on my fork. Initially thought I'd make all event types `LogValuer`s, but then that left me twiddling my thumbs on what to do with the message parameter. The overlap between `String` and any event fields I'd put in a `slog.Group` is total, so I faced the unfortunate choice of a redundant message (`logger.Log(ctx, level, e.string, e)`), or a useless one(`logger.Log(ctx, level, "event", s)`), both of which were unsatisfying, especially since the events are relatively parsimonious and `String` is pretty good already. Also, there's no convenient `slog` interface to encompass an entire log record (message+attrs), so I eventually ended up making each event type a `LogLeveler` and then did something like: 

```
	// set up the default logging handlers
	if s.EventHook == nil {
		defaultLogger := slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
			AddSource: false,
		})).With("supervisor", supervisorName)
		s.EventHook = func(e Event) {
			defaultLogger.Log(context.Background(), e.Level(), e.String())
		}
	}
```
But most of them are at `slog.LevelError` anyway. I'd be interested in your take on it.

**Comment by bn-jbowers** [comment]
I can't really do that because adding it into the suture package requires me to impose a Go 1.21 constraint. I have to add it not only as a subpackage, but a sub _module_ as well, so the constraint is isolated to just that module. That'll be coming in soon.
